### PR TITLE
✨ allow nodejs version >=12.9.1

### LINKED ISSUE #3: relax nodejs version lock
This package is used in both node and browser environments, as it only serves the purpose of serving stubs, we don't need to lockdown the nodejs version to only `12.9.1`.

The main reason for this change is to allow services like `vercel` to build the application.

change

```
  "engines": {
    "node": "12.9.1",
    "yarn": "1"
  },
```

to

```
  "engines": {
    "node": ">=12.9.1",
    "yarn": "1"
  },
```

read more [here](https://vercel.com/docs/runtimes#official-runtimes/node-js/node-js-version)

### PR DESCRIPTION
**Pull request by nionis**
Fixes #3

### CODE REVIEW

**Comment by peterbraden** [comment]
mind changing the CI as well so we test it? I've been doing the same elsewhere, see https://github.com/hoprnet/hopr-testing/pull/8/files for example

**Comment by peterbraden** [comment]
Also do we need the develop  branch or can we just use master here? see https://github.com/hoprnet/hopr-workflows for example?

**Comment by nionis** [comment]
@peterbraden thanks for the feedback; I don't think we need a `develop` branch here, I am not sure if I created it or was already here 🤔

**Comment by robertkiel** [comment]
> Also do we need the develop branch or can we just use master here? see https://github.com/hoprnet/hopr-workflows for example?

Potentially not. Calling our "main" repo master highlights the fact that our software is under development and in a very earky stage. I think this has made more sense in the past. For now, we can continue with master

**Review by peterbraden — APPROVED** [review]

**Pull request merged**
